// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzwmpgbnoxaoodfcqnzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6d21wZ2Jub3hhb29kZmNxbnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzOTgwODMsImV4cCI6MjA3NTk3NDA4M30.2rCDfF12i9gFWE7hES3ddH52BuvHBQ8zX3oh91DlaLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});